### PR TITLE
add split and preprocess test

### PR DESCRIPTION
**Pull request by MDSFusionist**
Dear Team, 

I've developed a new test module to thoroughly validate our data preprocessing and splitting functionality. This test suite extends our existing tests to include checks for file creation, data integrity, correct train-test splitting, and the accuracy of our preprocessing steps (scaling and one-hot encoding).

Key Additions:

Assertions to ensure training and test data files are created and not empty.
Checks for the correct train-test split ratio.
Verifications for the correct application of scaling to numeric features and one-hot encoding to categorical features.

Please review the changes, and let me know if any further modifications are needed.

### CODE REVIEW

**Comment by sandygross** [comment]
Hi Doris, 
thanks for your work! 
There are some issues:
1. We are required to create our own helper data and not use the data that we have already used for the analysis. Would be great if you can modify that.
2. The file name should start with 'test..'
3. We should separate the actual function from the tests in a separate file

**Comment by MDSFusionist** [comment]
Hi Sandy, thanks for your suggestions. I have made changes accordingly. This branch should be ready to merge into main.

**Comment by joeywwwu** [comment]
Hi Doris, it looks great now！

**Comment by sandygross** [comment]
The only issue I see with this code is that it is hard to implement into our existing analysis. Maybe you could make it more specific to one of the exisiting code chunks?

**Pull request merged**
